/**
 * Building a complete accent palette from a single colour.
 *
 * <h2>Why this exists</h2>
 *
 * <p>The six palettes in {@code _ambient-accents.scss} are hand-made: eleven
 * steps each, with the step that becomes <em>the</em> accent nominated per
 * scheme because the answer is not the same for every hue. Letting someone
 * choose their own colour means producing all of that from one hex, to the same
 * standard — a picker that simply painted every button in whatever the user
 * chose would produce unreadable labels the first time somebody picked yellow.</p>
 *
 * <h2>The ramp</h2>
 *
 * <p>Built in OKLCH, not HSL. HSL's lightness is not lightness: at L=50% a
 * yellow is blinding and a blue is nearly black, so an HSL ramp lightens some
 * hues twice as fast as others and the steps stop meaning the same thing across
 * palettes. OKLab is perceptually uniform, so one ladder of lightness values
 * produces steps that <em>look</em> evenly spaced whatever the hue.</p>
 *
 * <p>The chosen colour is the 500 step, exactly — same lightness, same chroma,
 * same hue. Every other step moves away from it along the ladder, with chroma
 * tapering towards both ends because a fully saturated near-white or near-black
 * is not a colour any palette wants. Steps that fall outside sRGB are brought
 * back by reducing chroma alone, which keeps the hue and lightness intact; the
 * alternative, clipping the channels, shifts the hue and is how a generated
 * ramp ends up with one step that is visibly the wrong colour.</p>
 *
 * <h2>Nomination is a contrast measurement, not a constant</h2>
 *
 * <p>Which step becomes the accent is decided by measuring, exactly as the
 * hand-made palettes were: the light-mode accent is the first step from 500
 * downwards whose contrast with white clears 4.5:1, which is why teal and
 * emerald nominate 700 where indigo nominates 600. The dark-mode accent is the
 * first step from 400 upwards that clears 4.5:1 against a dark surface. So a
 * custom colour cannot produce an unreadable button — the worst it can do is
 * produce a darker or lighter button than the user expected.</p>
 *
 * <h2>Output</h2>
 *
 * <p>{@link buildAccentRamp} returns the custom properties to write onto an
 * element — exactly the set {@code accent-palette()} emits in Sass, under
 * exactly the same names. That is what lets a generated palette and a built-in
 * one be the same thing downstream: nothing in the product knows the difference,
 * because nothing in the product reads anything but {@code --amb-accent-*}.</p>
 */

/** The eleven steps every palette has, light to dark. */
const RAMP_STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;

/**
 * Where each step sits relative to the chosen colour, which is 0.
 *
 * <p>Negative is lighter, positive is darker, and the two ends are 1.0 — so a
 * step's lightness is a straight interpolation between the chosen colour and
 * whichever end of the scale it is heading for. The spacing is slightly wider
 * near the middle than at the extremes, which is what keeps 400 and 600
 * distinguishable from 500 while 50 and 100 stay close together.</p>
 */
const STEP_POSITION: Record<number, number> = {
  50: -1, 100: -0.84, 200: -0.64, 300: -0.42, 400: -0.2,
  500: 0,
  600: 0.22, 700: 0.44, 800: 0.62, 900: 0.78, 950: 1
};

/**
 * How much of the chosen colour's chroma each step keeps.
 *
 * <p>It peaks across 500-600 and falls away towards both ends. A 50 step at
 * full chroma is a bright pastel rather than a tint, and a 950 at full chroma
 * is a muddy near-black; both are the marks of a ramp generated by changing
 * lightness alone.</p>
 */
const STEP_CHROMA: Record<number, number> = {
  50: 0.14, 100: 0.26, 200: 0.46, 300: 0.68, 400: 0.88,
  500: 1,
  600: 1, 700: 0.94, 800: 0.84, 900: 0.72, 950: 0.48
};

/** Where the ladder is heading at each end. Not 1 and 0: neither white nor
    black is a palette step, and stopping short is what leaves 50 a tint and 950
    a colour rather than a shade of grey. */
const LIGHT_END = 0.975;
const DARK_END = 0.22;

/**
 * The band the chosen colour is treated as sitting in, for ramp construction.
 *
 * <p>Someone who picks near-black or near-white as their primary colour still
 * needs eleven distinguishable steps, and an unclamped ladder would compress
 * everything on one side of the anchor into the same near-black or the same
 * near-white. Clamping only moves where the ramp is <em>centred</em>; which
 * step the interface actually paints with is still decided by contrast further
 * down.</p>
 *
 * <p>The band is wide on purpose. Narrowing it makes the ramp tidier and the
 * chosen colour less recognisable, and the chosen colour is the point — at
 * 0.80 a bright yellow-green came back thirty counts darker than what the user
 * had picked, because perceptual lightness runs far higher for yellows than the
 * HSL lightness people expect. These bounds hold every seed that is genuinely a
 * colour and clamp only the ones approaching black or white.</p>
 */
const ANCHOR_MIN = 0.35;
const ANCHOR_MAX = 0.88;

/** Below this there is no hue to preserve, and the pick is a deliberate grey. */
const GREY_CHROMA = 0.02;

/** A pale pick still has to produce a usable ramp; a grey one does not. */
const MIN_CHROMA = 0.08;

/** The ratio every nominated step has to clear against its own background. */
const MIN_CONTRAST = 4.5;

/**
 * The ground a dark-mode accent is measured against: `--amb-surface-2` over
 * `--amb-canvas`, which is the darkest surface the accent is ever drawn on.
 */
const DARK_REFERENCE: Rgb = { r: 22, g: 27, b: 43 };

interface Rgb {
  r: number;
  g: number;
  b: number;
}

interface Oklch {
  l: number;
  c: number;
  h: number;
}

/** A generated palette, ready to apply. */
export interface AmbientAccentRamp {
  /** The colour it was generated from, as `#rrggbb`. */
  readonly seed: string;

  /**
   * Custom property name to value, covering everything
   * {@code accent-palette()} declares. Values are literal colours rather than
   * `var()` references, so the map can be stored and replayed before the
   * application has booted.
   */
  readonly properties: Readonly<Record<string, string>>;
}

/**
 * Normalises a colour to `#rrggbb`, or returns null if it is not one.
 *
 * <p>Accepts the three-digit shorthand and a missing `#`, because both are
 * things people paste. Everything else is rejected rather than guessed at.</p>
 */
export function normaliseHex(value: string): string | null {
  const raw = value.trim().replace(/^#/, '').toLowerCase();

  if (/^[0-9a-f]{3}$/.test(raw)) {
    return `#${raw[0]}${raw[0]}${raw[1]}${raw[1]}${raw[2]}${raw[2]}`;
  }

  return /^[0-9a-f]{6}$/.test(raw) ? `#${raw}` : null;
}

/**
 * Builds a complete palette from one colour.
 *
 * @param seed any hex colour, with or without the `#`.
 * @returns the palette, or null if the seed is not a colour.
 */
export function buildAccentRamp(seed: string): AmbientAccentRamp | null {
  const hex = normaliseHex(seed);
  if (!hex) {
    return null;
  }

  const base = rgbToOklch(hexToRgb(hex));

  // A deliberate grey keeps its (absent) chroma. Anything with a hue is lifted
  // to a floor, so a pick of pale lilac still produces a palette with a 600 a
  // button can be painted in rather than eleven shades of off-white.
  const chroma = base.c < GREY_CHROMA ? base.c : Math.max(base.c, MIN_CHROMA);
  const anchor = clamp(base.l, ANCHOR_MIN, ANCHOR_MAX);

  const ramp = new Map<number, Rgb>();
  for (const step of RAMP_STEPS) {
    const position = STEP_POSITION[step];
    const end = position < 0 ? LIGHT_END : DARK_END;

    ramp.set(step, oklchToRgb({
      l: anchor + (end - anchor) * Math.abs(position),
      c: chroma * STEP_CHROMA[step],
      h: base.h
    }));
  }

  // The chosen colour is deliberately *not* pasted back over step 500.
  //
  // For any seed inside the anchor band it would change nothing: step 500 is
  // generated at the seed's own lightness, chroma and hue, and the round trip
  // through OKLab reproduces it to within a single 8-bit count. For a seed
  // outside the band it would actively break the ramp — the ladder is centred
  // on the clamped anchor, so a very light yellow dropped into slot 500 lands
  // above the 400 above it and the palette stops running light to dark.
  const light = nominate(ramp, [500, 600, 700, 800, 900], () => WHITE);
  const dark = nominate(ramp, [400, 300, 200, 100], () => DARK_REFERENCE);

  return { seed: hex, properties: propertiesFor(ramp, light, dark) };
}

// --- nomination -------------------------------------------------------------

const WHITE: Rgb = { r: 255, g: 255, b: 255 };

/**
 * The first step in `order` that clears 4.5:1 against its background, with the
 * step after it as the hover.
 *
 * <p>Falling back to the last candidate rather than failing is deliberate: a
 * palette that cannot clear the ratio anywhere is still better applied than
 * refused, and the fallback is by construction the most extreme step available
 * — the closest the chosen colour can get to legible.</p>
 */
function nominate(
  ramp: Map<number, Rgb>,
  order: readonly number[],
  background: () => Rgb
): { base: number; hover: number } {
  const ground = background();
  const index = order.findIndex(
    (step) => contrastRatio(ramp.get(step)!, ground) >= MIN_CONTRAST
  );

  const chosen = index === -1 ? order.length - 1 : index;

  // The hover is one step further along the same direction — darker for the
  // light-mode accent, lighter for the dark-mode one — so it always moves away
  // from its background rather than towards it.
  return {
    base: order[chosen],
    hover: order[Math.min(chosen + 1, order.length - 1)]
  };
}

function propertiesFor(
  ramp: Map<number, Rgb>,
  light: { base: number; hover: number },
  dark: { base: number; hover: number }
): Record<string, string> {
  const properties: Record<string, string> = {};

  for (const [step, rgb] of ramp) {
    properties[`--amb-accent-${step}`] = toHex(rgb);
  }

  // The same four-per-scheme contract `accent-palette()` emits. `on-soft` is
  // what gets written *on* an accent tint rather than on the accent itself —
  // the hover step in light, the accent step in dark. Using one value for both
  // is the single most common way a themeable palette breaks in dark mode.
  properties['--amb-accent-light'] = toHex(ramp.get(light.base)!);
  properties['--amb-accent-light-hover'] = toHex(ramp.get(light.hover)!);
  properties['--amb-accent-light-rgb'] = toTriplet(ramp.get(light.base)!);
  properties['--amb-accent-on-soft-light'] = toHex(ramp.get(light.hover)!);

  properties['--amb-accent-dark'] = toHex(ramp.get(dark.base)!);
  properties['--amb-accent-dark-hover'] = toHex(ramp.get(dark.hover)!);
  properties['--amb-accent-dark-rgb'] = toTriplet(ramp.get(dark.base)!);
  properties['--amb-accent-on-soft-dark'] = toHex(ramp.get(dark.base)!);

  return properties;
}

// --- colour space -----------------------------------------------------------
//
// sRGB ⇄ linear sRGB ⇄ OKLab ⇄ OKLCH. The matrices are Björn Ottosson's
// published OKLab constants; they are transcribed rather than derived, and
// there is nothing to tune in them.

function hexToRgb(hex: string): Rgb {
  const value = Number.parseInt(hex.slice(1), 16);
  return { r: (value >> 16) & 255, g: (value >> 8) & 255, b: value & 255 };
}

function toHex({ r, g, b }: Rgb): string {
  const channel = (value: number) => Math.round(value).toString(16).padStart(2, '0');
  return `#${channel(r)}${channel(g)}${channel(b)}`;
}

/** The `r g b` form, so an alpha tint can be mixed inline as `rgb(… / a)`. */
function toTriplet({ r, g, b }: Rgb): string {
  return `${Math.round(r)} ${Math.round(g)} ${Math.round(b)}`;
}

function toLinear(channel: number): number {
  const value = channel / 255;
  return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
}

function fromLinear(value: number): number {
  const channel = value <= 0.0031308 ? value * 12.92 : 1.055 * value ** (1 / 2.4) - 0.055;
  return clamp(channel, 0, 1) * 255;
}

function rgbToOklch(rgb: Rgb): Oklch {
  const r = toLinear(rgb.r);
  const g = toLinear(rgb.g);
  const b = toLinear(rgb.b);

  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);

  const lightness = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const a = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const bb = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;

  return {
    l: lightness,
    c: Math.sqrt(a * a + bb * bb),
    h: Math.atan2(bb, a)
  };
}

/** OKLab → linear sRGB, with no gamut handling. Its callers do that. */
function oklabToLinear(l: number, a: number, b: number): [number, number, number] {
  const lCube = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const mCube = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const sCube = (l - 0.0894841775 * a - 1.291485548 * b) ** 3;

  return [
    4.0767416621 * lCube - 3.3077115913 * mCube + 0.2309699292 * sCube,
    -1.2684380046 * lCube + 2.6097574011 * mCube - 0.3413193965 * sCube,
    -0.0041960863 * lCube - 0.7034186147 * mCube + 1.707614701 * sCube
  ];
}

/**
 * OKLCH → sRGB, brought into gamut by reducing chroma.
 *
 * <p>Chroma is the only thing given up. Clipping the channels instead is what
 * produces the one step in a generated ramp that is visibly the wrong colour: a
 * saturated blue whose blue channel clips comes back as violet, because the
 * other two channels did not clip with it. Halving the interval eight times
 * lands within about 0.4% of the most saturated colour that fits, which is
 * below the resolution of an 8-bit channel.</p>
 */
function oklchToRgb({ l, c, h }: Oklch): Rgb {
  let low = 0;
  let high = c;
  let best: [number, number, number] = oklabToLinear(l, 0, 0);

  if (inGamut(oklabToLinear(l, Math.cos(h) * c, Math.sin(h) * c))) {
    best = oklabToLinear(l, Math.cos(h) * c, Math.sin(h) * c);
  } else {
    for (let i = 0; i < 8; i++) {
      const mid = (low + high) / 2;
      const candidate = oklabToLinear(l, Math.cos(h) * mid, Math.sin(h) * mid);

      if (inGamut(candidate)) {
        best = candidate;
        low = mid;
      } else {
        high = mid;
      }
    }
  }

  return { r: fromLinear(best[0]), g: fromLinear(best[1]), b: fromLinear(best[2]) };
}

/** A hair of tolerance, so a colour that is in gamut to eight decimal places is
    not rejected by floating-point noise in the last one. */
function inGamut([r, g, b]: [number, number, number]): boolean {
  return [r, g, b].every((channel) => channel >= -0.0001 && channel <= 1.0001);
}

// --- contrast ---------------------------------------------------------------

/** WCAG 2 relative luminance. */
function luminance({ r, g, b }: Rgb): number {
  return 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
}

/** WCAG 2 contrast ratio, 1:1 to 21:1. */
export function contrastRatio(a: Rgb, b: Rgb): number {
  const first = luminance(a);
  const second = luminance(b);
  const lighter = Math.max(first, second);
  const darker = Math.min(first, second);

  return (lighter + 0.05) / (darker + 0.05);
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}
